### ISSUE TITLE
Interface responds to a SCPI *idn only if it´s lowercase

### ISSUE THREAD

**Issue by g-user** [Twilight-Logic/AR488#14]
I have an old device that doesn´t responds to *idn.  So I set the interface to respond to that.

But the program sends the *IDN - command in uppercase, so the interface doesn´t react to this command.

My Solution:
change the line (837) 
if (strncmp(buffr, "*idn?", 5)==0) {

to

if (strncasecmp(buffr, "*idn?", 5)==0) {

**Comment by Twilight-Logic** [comment]
Thank you for your report. The change will be implemented in the next release.

**Comment by SheetLightning** [comment]
Correction applied in version 0.49.14.
