### ISSUE TITLE
Pg 10 of manual discreprency with AR488_config.h

### ISSUE THREAD

**Issue by Hoverhead** [Twilight-Logic/AR488#17]
"#ifdef __AVR__" in the manual shows two lines of " #endif" but the actual file has three lines of " #endif" .  So which is correct?  Do I remove or add a" #endif" ?

**Comment by Twilight-Logic** [comment]
There are three #if statements, so there should be three corresponding #endif statements. The manual is in error. I will correct it. Thank you for spotting the discrepancy and reporting it.
