### ISSUE TITLE
macro issue

### ISSUE THREAD

**Issue by grahamwoan** [Twilight-Logic/AR488#19]
This is a great project, and it worked first time for me, using a nano. I had one problem though: the macro 0 example ends the last line with \n\, but I found this gave an "Unrecognized command" error.  Changing to just \ (ie omitting the LF on the final line) fixed things. So
`
 #define MACRO_0 "\
 ++auto 3\n\
 ++read\
 "
`
works, but ending `++read\n\` does not.

**Comment by Twilight-Logic** [comment]
Thank you for reporting the problem. I believe I have identified the reason and will fix it in the next release.

**Comment by grahamwoan** [comment]
thanks!

**Comment by Twilight-Logic** [comment]
Fixed in version 0.50.00 onwards.
