### ISSUE TITLE
DEVNULL.h missing at compilation w/ solution 

### ISSUE THREAD

**Issue by SensorPlay** [Twilight-Logic/AR488#30]
Fresh install of Arduino IDE 2.0 and 1.8.19 generates a compile time error w/ AR488 0.51.09:

"DEVNULL.h missing"

solved by adding official DEVNULL library using Arduino IDE "Libraries Manager"

described more here:  https://www.arduino.cc/reference/en/libraries/devnull/

**Comment by Twilight-Logic** [comment]
That is the solution. Install the official DevNull library using the Libraries Manager. I have already added this information to the Readme and the manual so it will be included when the next update is published.

**Comment by Twilight-Logic** [comment]
Information about DEVNULL has now been added to the published ReadMe as well as the manual.
