### ISSUE TITLE
0.51.09 ++tmbus command returns "unrecognized command"

### ISSUE THREAD

**Issue by SensorPlay** [Twilight-Logic/AR488#31]
noticed tmbus is commented out at several places in source

ex;
AR488.ino:  line 981 //  { "tmbus",       3, tmbus_h     },
                 line 2192-2206 

AR488_GPIBbus.cpp  line 871  //   delayMicroseconds(AR488.tmbus);

AR488_GPIBbus.h  line 108  //        uint16_t tmbus;

I'm not quite a good enough programmer, so I went back down to a copy of 0.49.14 from the source archive.  Thanks.

also:  I've selected Nano, and Uno commented in config.h, if that makes a diff

**Comment by Twilight-Logic** [comment]
Code relating to tmbus has been removed from release 0.51.14. The entry for the ++tmbus command has been removed from the manual.
