### ISSUE TITLE
which is best MCU to choose from?

### ISSUE THREAD

**Issue by dreamcat4** [Twilight-Logic/AR488#36]
hello,
I have here 34401a and was just wondering which MCU is best option. For my own situation: i have a variety here. But do not want to be bothered too much with custom PCB. Unless it can be justified, for example to make a better compatibility etc.

PC runs linux

Please let me know what to choose. Many thanks

**Comment by Twilight-Logic** [comment]
Artag's solution using the Pro Micro board works just fine. I would recommend avoiding the CH340 chip if possible as it does not support serial handshaking . Genuine Arduino boards with a 16u2, or anything with a CP2102 or P2102 should work fine.
