### ISSUE TITLE
Ground

### ISSUE THREAD

**Issue by cabo** [Twilight-Logic/AR488#4]
Shouldn't the manual point out that it is good to have a ground connection?
(Or, actually, seven of them?)
Maybe too obvious to an EE :-)

**Comment by Twilight-Logic** [comment]
Thanks for pointing this out. The table in the manual was focused on the control and data bus wires but indeed the ground connection should not be omitted. I will be adding a couple of diagrams to the manual and will correct this oversight at he same time.
