### ISSUE TITLE
Escaped characters not being sent

### ISSUE THREAD

**Issue by Mike0Github** [Twilight-Logic/AR488#45]
I am getting incorrect characters when trying to read HP3478A calibration memory at locations 10 and 27.

I am writing Wxx\n (87,xx,10) to the AR488 where xx is the memory location from 0 to 255, for escaped characters I am writing (87,27,xx,10), but if xx is 10, 13, or 27 nothing is written to the bus.

Monitoring the GPIB bus with another AR488 it appears the numbers 10, 13 and 27 are not being sent on the bus even though they are escaped with 27 (0x1B).  Other numbers escaped with 27 get through to the bus.

Is this a firmware bug or am I doing something wrong?

**Comment by Twilight-Logic** [comment]
Mike, thank you for your report. Which version of the firmware are you using?

Could you please confirm which version of the firmware you are using please? There was a problem with this is previous version but it was fixed in the latest version.

**Comment by Mike0Github** [comment]
I'm using version 0.51.28

**Comment by Mike0Github** [comment]
I will install version 0.51.29 tomorrow and let you know.

**Comment by Mike0Github** [comment]
Tried it this morning.  Works perfectly now.
b.t.w. During earlier testing I found I had to set the HP3478A to "Stop Trigger" (send 'T4') else it would send voltage readings along with the calibration data.
Thanks for a great program.

**Comment by Twilight-Logic** [comment]
Thank you for the feedback. Glad it is working now.
